services:
  db:
    image: postgres:15-alpine
    container_name: roletalk_db
    environment:
      POSTGRES_USER: ${APP_POSTGRES_USER}
      POSTGRES_PASSWORD: ${APP_POSTGRES_PASSWORD}
      POSTGRES_DB: ${APP_POSTGRES_DB}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_POSTGRES_USER} -d ${APP_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  migrations:
    image: kukymbr/goose-docker:3.24.2
    container_name: roletalk_migrations
    restart: "no"
    env_file:
      - .env.prod
    environment:
      GOOSE_DRIVER: ${GOOSE_DRIVER}
      GOOSE_DBSTRING: ${GOOSE_DBSTRING}
      GOOSE_MIGRATION_DIR: /migrations
      GOOSE_TABLE: ${GOOSE_TABLE}
    volumes:
      - ./go-backend/migrations:/migrations:ro
    depends_on:
      db:
        condition: service_healthy
    command: ["up"]

  s3:
    image: minio/minio
    container_name: roletalk_s3
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123
    volumes:
      - ./s3_data:/data
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"

  go-api:
    build: ./go-backend
    container_name: go_api
    depends_on:
      - db
      - s3
      - tempo
      - loki
      - migrations
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - APP_POSTGRES_HOST=db
      - APP_MINIO_ENDPOINT=s3:9000
      - APP_AI_URL=http://assistant-api:8080/voice
    restart: always

  assistant-api:
    build: ./voice-assistant
    container_name: assistant_api
    depends_on:
      - go-api
    volumes:
      - ./voice-assistant/models/whisper:/app/models/whisper
      - ./voice-assistant/models/piper:/app/models/piper:roё
    environment:
      - APP_HF_TOKEN=${APP_HF_TOKEN}
      - APP_OLLAMA_URL=${APP_OLLAMA_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./go-backend/internal/infra/prometheus/prometheus.yml:/etc/prometheus:ro
    ports:
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel_collector
    command: ["--config=/etc/otel-config.yaml"] # Указываем путь к конфигу явно
    volumes:
      - ./infra/otel/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "13133:13133" # Health_check extension (чтобы проверять, жив ли он)
    depends_on:
      - tempo
      - loki
    restart: unless-stopped

  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./go-backend/internal/infra/tempo/tempo.yaml:/etc/tempo.yaml
    ports:
    - "3200:3200"
    - "4317:4317"
    - "4318:4318"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
      - loki
      - tempo
    ports:
      - "3000:3000"
    volumes:
      - ./go-backend/internal/infra/grafana/provisioning:/etc/grafana/provisioning