# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai/v1/ai.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ai/v1/ai.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61i/v1/ai.proto\x12\x05\x61i.v1\"j\n\x17ProcessVoiceTurnRequest\x12\x12\n\naudio_data\x18\x01 \x01(\x0c\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x15\n\rsystem_prompt\x18\x03 \x01(\t\x12\x12\n\nrequest_id\x18\x04 \x01(\t\"g\n\x18ProcessVoiceTurnResponse\x12\x1a\n\x12user_transcription\x18\x01 \x01(\t\x12\x18\n\x10\x61i_response_text\x18\x02 \x01(\t\x12\x15\n\rai_audio_data\x18\x03 \x01(\x0c\x32`\n\tAIService\x12S\n\x10ProcessVoiceTurn\x12\x1e.ai.v1.ProcessVoiceTurnRequest\x1a\x1f.ai.v1.ProcessVoiceTurnResponseB\x1fZ\x1dgo-backend/pkg/api/ai/v1;aiv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai.v1.ai_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\035go-backend/pkg/api/ai/v1;aiv1'
  _globals['_PROCESSVOICETURNREQUEST']._serialized_start=25
  _globals['_PROCESSVOICETURNREQUEST']._serialized_end=131
  _globals['_PROCESSVOICETURNRESPONSE']._serialized_start=133
  _globals['_PROCESSVOICETURNRESPONSE']._serialized_end=236
  _globals['_AISERVICE']._serialized_start=238
  _globals['_AISERVICE']._serialized_end=334
# @@protoc_insertion_point(module_scope)
