// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: api/proto/ai/v1/ai.proto

package aiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProcessVoiceTurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AudioData     []byte                 `protobuf:"bytes,1,opt,name=audio_data,json=audioData,proto3" json:"audio_data,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	SystemPrompt  string                 `protobuf:"bytes,3,opt,name=system_prompt,json=systemPrompt,proto3" json:"system_prompt,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessVoiceTurnRequest) Reset() {
	*x = ProcessVoiceTurnRequest{}
	mi := &file_api_proto_ai_v1_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVoiceTurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVoiceTurnRequest) ProtoMessage() {}

func (x *ProcessVoiceTurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ai_v1_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVoiceTurnRequest.ProtoReflect.Descriptor instead.
func (*ProcessVoiceTurnRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ai_v1_ai_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessVoiceTurnRequest) GetAudioData() []byte {
	if x != nil {
		return x.AudioData
	}
	return nil
}

func (x *ProcessVoiceTurnRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ProcessVoiceTurnRequest) GetSystemPrompt() string {
	if x != nil {
		return x.SystemPrompt
	}
	return ""
}

func (x *ProcessVoiceTurnRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ProcessVoiceTurnResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserTranscription string                 `protobuf:"bytes,1,opt,name=user_transcription,json=userTranscription,proto3" json:"user_transcription,omitempty"`
	AiResponseText    string                 `protobuf:"bytes,2,opt,name=ai_response_text,json=aiResponseText,proto3" json:"ai_response_text,omitempty"`
	AiAudioData       []byte                 `protobuf:"bytes,3,opt,name=ai_audio_data,json=aiAudioData,proto3" json:"ai_audio_data,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProcessVoiceTurnResponse) Reset() {
	*x = ProcessVoiceTurnResponse{}
	mi := &file_api_proto_ai_v1_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessVoiceTurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessVoiceTurnResponse) ProtoMessage() {}

func (x *ProcessVoiceTurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ai_v1_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessVoiceTurnResponse.ProtoReflect.Descriptor instead.
func (*ProcessVoiceTurnResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ai_v1_ai_proto_rawDescGZIP(), []int{1}
}

func (x *ProcessVoiceTurnResponse) GetUserTranscription() string {
	if x != nil {
		return x.UserTranscription
	}
	return ""
}

func (x *ProcessVoiceTurnResponse) GetAiResponseText() string {
	if x != nil {
		return x.AiResponseText
	}
	return ""
}

func (x *ProcessVoiceTurnResponse) GetAiAudioData() []byte {
	if x != nil {
		return x.AiAudioData
	}
	return nil
}

var File_api_proto_ai_v1_ai_proto protoreflect.FileDescriptor

const file_api_proto_ai_v1_ai_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/ai/v1/ai.proto\x12\x05ai.v1\"\x98\x01\n" +
	"\x17ProcessVoiceTurnRequest\x12\x1d\n" +
	"\n" +
	"audio_data\x18\x01 \x01(\fR\taudioData\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12#\n" +
	"\rsystem_prompt\x18\x03 \x01(\tR\fsystemPrompt\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"\x97\x01\n" +
	"\x18ProcessVoiceTurnResponse\x12-\n" +
	"\x12user_transcription\x18\x01 \x01(\tR\x11userTranscription\x12(\n" +
	"\x10ai_response_text\x18\x02 \x01(\tR\x0eaiResponseText\x12\"\n" +
	"\rai_audio_data\x18\x03 \x01(\fR\vaiAudioData2`\n" +
	"\tAIService\x12S\n" +
	"\x10ProcessVoiceTurn\x12\x1e.ai.v1.ProcessVoiceTurnRequest\x1a\x1f.ai.v1.ProcessVoiceTurnResponseB\x1fZ\x1dgo-backend/pkg/api/ai/v1;aiv1b\x06proto3"

var (
	file_api_proto_ai_v1_ai_proto_rawDescOnce sync.Once
	file_api_proto_ai_v1_ai_proto_rawDescData []byte
)

func file_api_proto_ai_v1_ai_proto_rawDescGZIP() []byte {
	file_api_proto_ai_v1_ai_proto_rawDescOnce.Do(func() {
		file_api_proto_ai_v1_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ai_v1_ai_proto_rawDesc), len(file_api_proto_ai_v1_ai_proto_rawDesc)))
	})
	return file_api_proto_ai_v1_ai_proto_rawDescData
}

var file_api_proto_ai_v1_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_ai_v1_ai_proto_goTypes = []any{
	(*ProcessVoiceTurnRequest)(nil),  // 0: ai.v1.ProcessVoiceTurnRequest
	(*ProcessVoiceTurnResponse)(nil), // 1: ai.v1.ProcessVoiceTurnResponse
}
var file_api_proto_ai_v1_ai_proto_depIdxs = []int32{
	0, // 0: ai.v1.AIService.ProcessVoiceTurn:input_type -> ai.v1.ProcessVoiceTurnRequest
	1, // 1: ai.v1.AIService.ProcessVoiceTurn:output_type -> ai.v1.ProcessVoiceTurnResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_ai_v1_ai_proto_init() }
func file_api_proto_ai_v1_ai_proto_init() {
	if File_api_proto_ai_v1_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ai_v1_ai_proto_rawDesc), len(file_api_proto_ai_v1_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ai_v1_ai_proto_goTypes,
		DependencyIndexes: file_api_proto_ai_v1_ai_proto_depIdxs,
		MessageInfos:      file_api_proto_ai_v1_ai_proto_msgTypes,
	}.Build()
	File_api_proto_ai_v1_ai_proto = out.File
	file_api_proto_ai_v1_ai_proto_goTypes = nil
	file_api_proto_ai_v1_ai_proto_depIdxs = nil
}
